### ISSUE TITLE
Enable hourly billing on Amazon

### ISSUE THREAD

**Issue by rsignell-usgs** [robfatland/costnotify#3]
I noticed in the AWS cost explorer there is a greyed-out option for "hourly" costs
![2020-02-03_8-43-54](https://user-images.githubusercontent.com/1872600/73686742-99f17b80-4696-11ea-840c-769c710ebdfb.png)
and it says it can be enabled in account settings, but in account settings, I see: "Account settings are only available for Payer and Regular Accounts."  So I'm not sure if we can, but if we could enable it seems like it would be useful for tutorials and demos to have hourly accounting.

**Comment by robfatland** [comment]
I presume you are referring to the Pangeo account? I believe this is a shortcoming of going through our particular reseller. (One can check out any time one likes...) 

Just to reiterate what's happening in this repo: 

Account burn data are accumulated hourly by the re-seller DLT using CloudCheckr into an S3 bucket CSV file. This file is then parsed daily by the costnotify lambda function on a timer; but not comprehensively yet. It sends an email summary. I use this to keep a "daily glance" at the account burn rate for about six accounts. That code runs as a `costnotify` lambda in N.Virginia. This may sound reasonable but it does suffer from the accumulation rate lagging the actual burn by about 2 days; so we only see what we spent 2 days ago or later with any accuracy. That said: If anyone would like to improve the parsing code found here that'd be most welcome.

**Comment by rsignell-usgs** [comment]
@robfatland thanks for the education.  I had no idea -- I thought just the regular AWS cost tools were being used.
